(cl:in-package #:cluffer-test)

(defun make-update-trace (buffer time)
  (let ((result '()))
    (flet ((sync (line)
	     (push `(sync ,(cluffer:item-count line)) result))
	   (skip (n)
	     (push `(skip ,n) result))
	   (modify (line)
	     (push `(modify ,(cluffer:item-count line)) result))
	   (create (line)
	     (push `(create ,(cluffer:item-count line)) result)))
      (cluffer:update buffer time #'sync #'skip #'modify #'create)
      (nreverse result))))

